name: step1

on: push

jobs: 
  run_tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
          api-level: 29
          script: ./gradlew connectedCheck
    
