name: step1

on: push

jobs: 
  run_tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: | 
         chmod +x ./vdrun.sh
         ./vdrun.sh
      shell: bash
