name: step1

on: push

jobs:
  build:
    runs-on: macos-latest
   
    steps:
      - run: |
         mkdir andsdk
         cd andsdk
         brew install --cask android-commandlinetools
         avdmanager create avd -n test -k "system-images;android-30;google_atd;arm64-v8a
