name: step1

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
     working-directory: ./dir1

    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:
      - run: |
         cd ${{ env.working-directory }}
         pwd # will respect working-directory
