name: step1

on: push

jobs: 
  Selenium_test:    
   runs-on:  macos-latest
   
   steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run inline script
        run: |
          mkdir hai
          ls -l
      - name: Run inline script
        run: cd hai
             npm install hai
