name: step1

on: push

jobs:
  build:
    runs-on: macos-latest
   
    steps:
      - run: |
         mkdir andsdk
         cd andsdk
         brew install --cask android-commandlinetools
         avdmanager --verbose create avd --force --name "pixel_5_api30_google_atd_emulator" --package "system-images;android-30;google_atd;arm64-v8a" --tag "google_atd" --abi "arm64-v8a" --device "pixel_5"
