name: step1

on: push

jobs: 
  Selenium_test:    
   runs-on:  macos-latest
   strategy:
      matrix:
        api-level: [29]
   
   steps:
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run inline script
        run: |
          mkdir hai
          ls -l
          
      - name: get folder details
        run: |
            sdkmanager --install "system-images;android-30;google_atd;arm64-v8a"
           
      - name: Run install node
        run: |
             cd hai
             npm install hai
      - name: get node version script
        run: |
            cd hai
            node --version
      - name: install Appium script
        run: |
            cd hai
            npm install -g appium
      - name: get Appium version
        run: |
            cd hai
            appium --version
      - name: install Appium Doctor
        run: |
            cd hai
            npm install appium-doctor -g
      - name: get Appium Doctor deatils
        run: |
            cd hai
            appium-doctor
      - name: get Appium driver
        run: |
            xcrun simctl list
      - name: Create AVD snapshot
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
                  api-level: ${{ matrix.api-level }}
                  arch: ${{ steps.avd-info.outputs.arch }}
                  target: ${{ steps.avd-info.outputs.target }}
                  disable-animations: false
                  force-avd-creation: false
                  ram-size: 4096M
                  emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
                  script: echo "Generated AVD snapshot."
                  
